### ISSUE TITLE
Not possible to login

### ISSUE THREAD

**Issue by andre-paulo98** [adigitalife/yourls-allow-aliases#4]
It seems to be impossible to login on a Alias address.
I have my.long.address.com on the config.php and the Allow aliases plugin enabled. 
Login on my.long.address.com works fine, but using a Alias seems to not work.
Using the short links works.

**Comment by silver-hopla** [comment]
any update to this? I have the same issue.

**Comment by adigitalife** [comment]
This plugin is not intended for login support.  It's only for the short links so that old.domain/link continues to work in addition to new.domain/link.

Actually, I'm not sure why it's necessary to login to old.domain when you can login to new.domain.  To me, what matters is that the short links work for both old.domain and new.domain.  At least that's the use case for me and it's why I made this plugin.
